// Copyright (c) 2023, Radome Technologies and Services Private Limited
// All rights reserved.

// FileName: theme.js
// Description: Theme ui, custom theme setup here,
// Author: Nithish Kumar K,
// Revision dates: 11-05-2023,
// List of components: NIL,
// Approved by: Ajit,
// Date of Approval: 11-05-2023,

// Redistribution and use in source and binary forms, with or without modification, are strictly prohibited without prior written permission from Radome Technologies and Services Private Limited

/* eslint-disable import/no-anonymous-default-export */

export default {
  breakpoints: ["350px", "992px", "1200px", "1650px"],
  colors: {
    primary: "#2dbece",
    secondary: "#3b4859",
    highLight: "#176169",
    bg: "#eaf8fa",
    footerBgColor: "#165f67",
    divider: "rgba(255,255,255, 0.3);",
    footerPrimaryBg: "#81d8e1",
  },
  fonts: {
    poppins: "Poppins",
    breeSerif: "Bree Serif",
  },
  sizes: {
    desktopContainer: 1600,
  },
  images: {
    logo: {
      width: ["180px", "180px", "250px"],
      height: "auto",
    },
    menuIcon: {
      width: [32, 32, 0],
      height: [32, 32, 0],
    },
  },
  fontWeights: {
    ultraLight: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
    extraBold: 900,
  },
  text: {
    mainHeader: {
      fontSize: ["18px", "18px", "20px"],
      fontFamily: "Poppins",
      lineHeight: ["16px", "16px", "heading"],
      fontWeight: "medium",
      letterSpacing: "1px",
      textDecoration: "none",
      color: "black",
    },
    heading: {
      fontSize: [20, 20, 30],
      fontWeight: 500,
      color: "highLight",
      mb: [30, 30, 30],
      textAlign: "center",
      fontFamily: "breeSerif",
    },
    title: {
      fontSize: [16, 16, 20],
      lineHeight: "auto",
      fontWeight: 500,
      color: "secondary",
      fontFamily: "poppins",
      textAlign: ["center", "center", "left"],
    },
    description: {
      fontSize: [12, 12, 13],
      fontWeight: 400,
      color: "secondary",
      fontFamily: "poppins",
      textAlign: ["justify", "justify", "left"],
    },
    sm: {
      fontSize: ["18px", "18px", "18px"],
      fontWeight: "semiBold",
      lineHeight: "20px",
      color: "#1B2227",
      fontFamily: "Poppins",
    },
    xs: {
      fontSize: ["18px", "18px", "18px"],
      fontWeight: "400",
      lineHeight: ["28px", "28px", "36px"],
      color: "#1B2227",
      fontFamily: "Poppins",
    },
  },
  buttons: {
    normal_text_btn: {
      fontSize: [16, 16, 16],
      fontWeight: 700,
      color: "primary",
      fontFamily: "Poppins",
      border: "none",
      background: "transparent",
      cursor: "pointer",
      padding: 0,
    },
    solid_primary: {
      fontSize: [16, 16, 18],
      fontWeight: 500,
      color: "#1F232E",
      transition: `transform 250ms`,
      background: "primary",
      lineHeight: "22.5px",
      fontFamily: "Poppins",
      borderRadius: 25,
      border: "none",
      padding: 15,
      cursor: "pointer",
      minWidth: [130, 130, 180],
      "&:hover": {
        transform: "scale(1.1)",
      },
    },
    outline_primary: {
      borderRadius: 25,
      border: "1px solid ",
      borderColor: "white",
      color: "white",
      fontSize: "14px",
      fontWeight: 500,
      fontFamily: "Poppins",
      cursor: "pointer",
      padding: '8px',
      background: "transparent",
    },
  },
  iconwithhover: (props) => ({
    backgroundColor: "#3b4859",
    margin: 2,
    border: "2px solid #eaebf0",
    borderRadius: "50%",
    padding: 10,
    _focus: {
      boxShadow: "none !important",
    },
  }),
  links: {
    bold: {
      fontWeight: "normal",
      WebkitTapHighlightColor: "transparent",
    },
    nav: {
      fontSize: "16px",
      lineHeight: "24px",
      fontWeight: "normal",
      color: "#3b4859",
      paddingY: "35px",
      fontFamily: "Poppins",
      textDecoration: "none",
      borderBottom: "2px solid",
      borderColor: "transparent",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
      "&:hover,&:active": {
        color: "primary",
      },
    },
    footernav: {
      fontSize: ["18px", "18px", "18px"],
      fontWeight: "400",
      lineHeight: ["28px", "28px", "36px"],
      color: "#1B2227",
      textDecoration: "none",
      fontFamily: "Poppins",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
      mt: 15,
      overflowWrap: "break-word",
    },
    footerCopyNav: {
      fontSize: ["18px", "18px", "18px"],
      fontWeight: "400",
      lineHeight: ["28px", "28px", "36px"],
      color: "#1B2227",
      textDecoration: "none",
      fontFamily: "Poppins",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    normal: {
      fontSize: "14px",
      fontWeight: "normal",
      lineHeight: "21px",
      color: "white",
      textDecoration: "none",
      fontFamily: "Poppins",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    line: {
      fontSize: "16px",
      fontWeight: "600",
      lineHeight: "24px",
      color: "white",
      fontFamily: "Poppins",
      cursor: "pointer",
      textDecoration: "underline",
      WebkitTapHighlightColor: "transparent",
    },
    mainLink: {
      fontSize: "20px",
      fontFamily: "Poppins",
      lineHeight: "heading",
      fontWeight: "medium",
      letterSpacing: "1px",
      textDecoration: "none",
      color: "black",
      fontFamily: "Poppins",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    nav2: {
      fontSize: ["18px", "18px", "16px"],
      lineHeight: ["27px", "27px", "24px"],
      fontWeight: ["300", "300", "300"],
      color: "black",
      fontFamily: "Poppins",
      textDecoration: "none",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
      "&:hover &:active": {
        color: "primary",
        fontSize: ["24px", "24px", "16px"],
        lineHeight: ["36px", "36px", "24px"],
        fontWeight: ["medium", "medium", "medium"],
      },
    },
    navNormal: {
      fontSize: "15px",
      fontWeight: "normal",
      lineHeight: "30px",
      textAlign: "justified",
      fontFamily: "Poppins",
      color: "blue",
      textDecoration: "none",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    viewNav: {
      fontSize: "16px",
      lineHeight: "24px",
      fontWeight: "normal",
      fontFamily: "Poppins",
      color: "blue",
      textDecoration: "none",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    xsLink: {
      fontSize: "14px",
      fontWeight: "300",
      lineHeight: "36px",
      color: "white",
      fontFamily: "Poppins",
      textDecoration: "none",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
    mdLink: {
      fontSize: ["14px", "14px", "18px"],
      fontWeight: "medium",
      lineHeight: ["24px", "24px", "27px"],
      color: "blue",
      fontFamily: "Poppins",
      textDecoration: "none",
      cursor: "pointer",
      WebkitTapHighlightColor: "transparent",
    },
  },
};
